ASP_MVC/Controllers/AuthController.cs
using ASP_MVC.Handlers;
using ASP_MVC.Models.Auth;
using BLL_Khaoula.Entities;
using Commun.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace ASP_MVC.Controllers
{
    public class AuthController : Controller
    {
        private IUserRepository<BLL_Khaoula.Entities.User> _userService;
        private SessionManager _sessionManager;

        public AuthController(IUserRepository<User> userService, SessionManager sessionManager)
        {
            _userService = userService;
            _sessionManager = sessionManager;
        }

        public IActionResult Index()
        {
            return RedirectToAction(nameof(Login));
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login (AuthLoginForm form)
        {
            try
            {
                if (!ModelState.IsValid) throw new ArgumentException(nameof(form));
                Guid id = _userService.CheckPassword(form.Email,form.Password);
                ConnectedUser user = new ConnectedUser()
                {
                    User_id = id,
                    Email = form.Email,
                    ConnectedAt = DateTime.Now
                };
                _sessionManager.Login(user);
                return RedirectToAction("Details","User", new {id=id});

            }
            catch (Exception)
            {

                throw;
            }
        }

        public IActionResult Logout() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult Logout(IFormCollection form)
        {
            try
            {
                _sessionManager.Logout();
                return RedirectToAction(nameof(Login));
            }
            catch (Exception)
            {

                return View();
            }
        }
    }
}

ASP_MVC/Controllers/CocktailController.cs
using ASP_MVC.Mappers;
using ASP_MVC.Models.Cocktail;
using BLL_Khaoula.Entities;
using BLL_Khaoula.Services;
using Commun.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ASP_MVC.Controllers
{
    public class CocktailController : Controller
    {
        private ICocktailRepository<Cocktail> _service;
        public CocktailController(ICocktailRepository<Cocktail> service)
        {
            _service = service;
        }
        // GET: CocktailController
        public ActionResult Index()
        {
            try
            {

                IEnumerable<CocktailListItem> model = _service.Get().Select(b => b.ToListItem());
                return View(model);
            }
            catch (Exception ex) 
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // GET: CocktailController/Details/5
        public ActionResult Details(Guid id)
        {
            try
            {
                CocktailDetails model = _service.GetById(id).ToDetails();
                return View(model);
            }
            catch (Exception ex)
            {

                return RedirectToAction("Error", "Home");
            }
        }

        // GET: CocktailController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CocktailController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CocktailCreateForm form)
        {
            try
            {
                if (!ModelState.IsValid) throw new ArgumentException(nameof(form));
                Guid id =_service.Insert(form.ToBLL());

                return RedirectToAction(nameof(Details), new {id});
            }
            catch
            {
                return View();

            }
        }

        // GET: CocktailController/Edit/5
        public ActionResult Edit(Guid id)
        {
            try
            {
                CocktailEditForm model = _service.GetById(id).ToEditForm();
                return View(model);
            }
            catch (Exception ex)
            {

                return RedirectToAction(nameof(Index));
            }
        }

        // POST: CocktailController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Guid id, CocktailEditForm form)
        {
            try
            {
                if (!ModelState.IsValid) throw new ArgumentException(nameof(form));
                _service.Update(id,form.ToBLL());
                return RedirectToAction(nameof(Details),new {id});
            }
            catch
            {
                return View();
            }
        }

        // GET: CocktailController/Delete/5
        public ActionResult Delete(Guid id)
        {
            try
            {
                CocktailDelete model = _service.GetById(id).ToDeleteForm();
                return View(model);
            }
            catch (Exception ex)
            {

                return RedirectToAction(nameof(Index));
            }
        }

        // POST: CocktailController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, CocktailDelete form)
        {
            try
            {
                _service.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ASP_MVC/Views/Shared/_CocktailsList.cshtml
@model IEnumerable<ASP_MVC.Models.Cocktail.CocktailListItem>

<p>
    <a asp-action="Create" asp-asp-controller="Cocktail">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit","Cocktail", new { id=item.Cocktail_id }) |
                    @Html.ActionLink("Details", "Details", "Cocktail", new { id = item.Cocktail_id }) |
                    @Html.ActionLink("Delete", "Delete", "Cocktail", new { id = item.Cocktail_id })
            </td>
        </tr>
}
    </tbody>
</table>

ASP_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @* <li class="nav-item"> *@
                        @*     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
                        @* </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cocktail" asp-action="Index">Cocktails</a>
                        </li>
                        @if (sessionManager.ConnectedUser is null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Create">S'enregister'</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Se connecter</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Se deconnecter</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ASP_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>